# Generated by Django 2.2.4 on 2019-08-09 02:45

import DiurenCloud.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudDirectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, validators=[DiurenCloud.validators.validate_object_name_special_characters])),
                ('virtual_name', models.CharField(max_length=128, validators=[DiurenCloud.validators.validate_object_name_special_characters])),
                ('path', models.CharField(max_length=256)),
                ('virtual_path', models.CharField(max_length=256)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CloudUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '云用户',
                'verbose_name_plural': '云用户',
            },
        ),
        migrations.CreateModel(
            name='CloudFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, validators=[DiurenCloud.validators.validate_object_name_special_characters])),
                ('virtual_name', models.CharField(max_length=128, validators=[DiurenCloud.validators.validate_object_name_special_characters])),
                ('path', models.CharField(max_length=256)),
                ('virtual_path', models.CharField(max_length=256)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='DiurenCloud.CloudUser')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='DiurenCloud.CloudDirectory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='clouddirectory',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directories', to='DiurenCloud.CloudUser'),
        ),
        migrations.AddField(
            model_name='clouddirectory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directories', to='DiurenCloud.CloudDirectory'),
        ),
    ]
