# Generated by Django 2.2.3 on 2019-08-05 06:07

import DiurenCloud.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudDirectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(auto_created=True, max_length=256, unique=True, verbose_name='路径')),
                ('date_updated', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=128, validators=[DiurenCloud.validators.validate_object_name_special_characters])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directories', to='DiurenCloud.CloudDirectory', verbose_name='上级文件夹')),
            ],
            options={
                'verbose_name': '云文件夹',
            },
        ),
        migrations.CreateModel(
            name='CloudUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CloudFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(auto_created=True, max_length=256, unique=True, verbose_name='路径')),
                ('date_updated', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=128, validators=[DiurenCloud.validators.validate_object_name_special_characters])),
                ('size', models.PositiveIntegerField(verbose_name='文件大小')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='DiurenCloud.CloudDirectory', verbose_name='上级文件夹')),
            ],
            options={
                'verbose_name': '云文件',
            },
        ),
    ]
