# Generated by Django 2.2.3 on 2019-08-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiurenCloud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clouddirectory',
            name='path',
            field=models.CharField(auto_created=True, max_length=256, verbose_name='路径'),
        ),
        migrations.AlterField(
            model_name='cloudfile',
            name='path',
            field=models.CharField(auto_created=True, max_length=256, verbose_name='路径'),
        ),
    ]
