# Generated by Django 2.2.3 on 2019-08-06 01:27

import DiurenCloud.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DiurenCloud', '0002_auto_20190805_1423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clouddirectory',
            options={'verbose_name': '云文件夹', 'verbose_name_plural': '云文件夹'},
        ),
        migrations.AlterModelOptions(
            name='cloudfile',
            options={'verbose_name': '云文件', 'verbose_name_plural': '云文件'},
        ),
        migrations.AlterModelOptions(
            name='clouduserprofile',
            options={'verbose_name': '云用户档案', 'verbose_name_plural': '云用户档案'},
        ),
        migrations.AlterField(
            model_name='clouddirectory',
            name='name',
            field=models.CharField(max_length=128, validators=[DiurenCloud.validators.validate_object_name_special_characters], verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='clouddirectory',
            name='path',
            field=models.CharField(auto_created=True, editable=False, max_length=256, verbose_name='路径'),
        ),
        migrations.AlterField(
            model_name='cloudfile',
            name='name',
            field=models.CharField(max_length=128, validators=[DiurenCloud.validators.validate_object_name_special_characters], verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='cloudfile',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='DiurenCloud.CloudDirectory', verbose_name='上级文件夹'),
        ),
        migrations.AlterField(
            model_name='cloudfile',
            name='path',
            field=models.CharField(auto_created=True, editable=False, max_length=256, verbose_name='路径'),
        ),
    ]
