# Generated by Django 2.2.4 on 2019-08-12 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiurenCloud', '0002_auto_20190809_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudfile',
            name='uploaded',
            field=models.BooleanField(auto_created=True, default=False),
        ),
    ]
