# Generated by Django 2.2.3 on 2019-08-06 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DiurenCloud', '0003_auto_20190806_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '云用户档案',
                'verbose_name_plural': '云用户档案',
            },
        ),
        migrations.AlterField(
            model_name='clouddirectory',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DiurenCloud.CloudUser', verbose_name='所有者'),
        ),
        migrations.AlterField(
            model_name='cloudfile',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DiurenCloud.CloudUser', verbose_name='所有者'),
        ),
        migrations.DeleteModel(
            name='CloudUserProfile',
        ),
    ]
