# Generated by Django 2.2.4 on 2019-08-12 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiurenCloud', '0003_cloudfile_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudfile',
            name='md5',
            field=models.CharField(default='ds430fif0escmxzorkfdov3o', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cloudfile',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cloudfile',
            name='uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
