# Generated by Django 2.2.3 on 2019-08-06 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DiurenCloud', '0004_auto_20190806_0938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clouduser',
            options={'verbose_name': '云用户', 'verbose_name_plural': '云用户'},
        ),
    ]
