# Generated by Django 2.2.4 on 2019-08-13 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiurenCloud', '0005_auto_20190813_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='clouddirectory',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
