# Generated by Django 2.2.4 on 2019-08-13 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiurenCloud', '0006_clouddirectory_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='clouddirectory',
            name='can_read_users',
            field=models.ManyToManyField(related_name='can_read_directories', to='DiurenCloud.CloudUser'),
        ),
        migrations.AddField(
            model_name='clouddirectory',
            name='can_write_users',
            field=models.ManyToManyField(related_name='can_write_directories', to='DiurenCloud.CloudUser'),
        ),
        migrations.AddField(
            model_name='clouddirectory',
            name='public_read',
            field=models.BooleanField(default=False, verbose_name='公共读'),
        ),
        migrations.AddField(
            model_name='cloudfile',
            name='can_read_users',
            field=models.ManyToManyField(related_name='can_read_files', to='DiurenCloud.CloudUser'),
        ),
        migrations.AddField(
            model_name='cloudfile',
            name='can_write_users',
            field=models.ManyToManyField(related_name='can_write_files', to='DiurenCloud.CloudUser'),
        ),
        migrations.AddField(
            model_name='cloudfile',
            name='public_read',
            field=models.BooleanField(default=False, verbose_name='公共读'),
        ),
    ]
