# Generated by Django 2.2.3 on 2019-08-05 06:06

import DiurenAccount.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DiurenAccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email_validation_tokens',
            field=DiurenAccount.fields.DictField(default={}),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='used_emails',
            field=DiurenAccount.fields.DictField(default={}),
        ),
    ]
