# Generated by Django 2.2.3 on 2019-08-06 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DiurenAccount', '0002_auto_20190805_1406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '用户资料', 'verbose_name_plural': '用户资料'},
        ),
    ]
